# Preparação do ambiente

In [1]:
%pip install pandas
%pip install openpyxl

Requirement already satisfied: pandas in c:\users\vhcna\onedrive - marca saúde\área de trabalho\freelas\flua nutrição\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vhcna\onedrive - marca saúde\área de trabalho\freelas\flua nutrição\venv\lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vhcna\onedrive - marca saúde\área de trabalho\freelas\flua nutrição\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vhcna\onedrive - marca saúde\área de trabalho\freelas\flua nutrição\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vhcna\onedrive - marca saúde\área de trabalho\freelas\flua nutrição\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vhcna\onedrive - marca saúde\área de trabalho\freelas\flua nutrição\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\vhcna\onedrive - marca saúde\área de trabalho\freelas\flua nutrição\venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\vhcna\onedrive - marca saúde\área de trabalho\freelas\flua nutrição\venv\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

# ETL

In [3]:
df_input_a = pd.read_excel(r'C:\Users\vhcna\OneDrive - Marca Saúde\Área de Trabalho\Freelas\Flua nutrição\arquivos originais\01 Disponibilidade Optum - cópia bruta do sistema.xlsx')
df_input_a.head()

,Dia,HORA INICIAL,HORA FINAL,HORAS TOTAIS,TIPO ATENDIMENTO,RESPONSÁVEL,Unnamed: 6
0,NaN,01/11/2025 - Sab,08:00:00,09:00:00,01:00:00,NaN,JULIANA RIBEIRO DE MELO
1,NaN,01/11/2025 - Sab,09:00:00,10:00:00,01:00:00,NaN,JULIANA RIBEIRO DE MELO
2,NaN,01/11/2025 - Sab,10:00:00,11:00:00,01:00:00,NaN,JULIANA RIBEIRO DE MELO
3,NaN,01/11/2025 - Sab,11:00:00,12:00:00,01:00:00,NaN,JULIANA RIBEIRO DE MELO
4,NaN,03/11/2025 - Seg,07:00:00,09:00:00,02:00:00,NaN,DANIELLE CASTELLANI

In [4]:
dict_mes = {1:'Janeiro', 2: 'Fevereiro', 3:'Março', 4:'Abril', 5:'Maio', 6:'Junho',
            7:'Julho', 8:'Agosto', 9:'Setembro', 10:'Outubro', 11:'Novembro', 12:'Dezembro'}

df_input_a_trd = pd.DataFrame(columns=['Data completa', 'Ano', 'Mês', 'Mês_Ano', 'DDS', 'Início', 'Fim', 'Total horas', 'Janelas','Nutri'])
df_input_a_trd['Data completa'] = df_input_a['HORA INICIAL'].copy()
df_input_a_trd["Data"] = df_input_a_trd["Data completa"].str.split(" -").str[0]
df_input_a_trd["Data"] = pd.to_datetime(df_input_a_trd["Data"], format="%d/%m/%Y", errors="coerce")
df_input_a_trd['Ano'] = df_input_a_trd["Data"].dt.year
df_input_a_trd['Mês_num'] = df_input_a_trd["Data"].dt.month
df_input_a_trd['Mês'] = df_input_a_trd['Mês_num'].map(dict_mes)
df_input_a_trd['Mês_Ano'] = df_input_a_trd['Mês'] + df_input_a_trd['Ano'].astype(str)
df_input_a_trd['DDS'] = df_input_a_trd['Data completa'].str[-3:]
df_input_a_trd['Início'] = df_input_a['HORA FINAL'].copy()
df_input_a_trd["Início"] = pd.to_datetime(df_input_a_trd["Início"], format="%H:%M:%S", errors="coerce")
df_input_a_trd['Fim'] = df_input_a['HORAS TOTAIS'].copy()
df_input_a_trd["Fim"]    = pd.to_datetime(df_input_a_trd["Fim"], format="%H:%M:%S", errors="coerce")
df_input_a_trd["Total horas"] = (df_input_a_trd["Fim"] - df_input_a_trd["Início"])
df_input_a_trd["Total horas"] = df_input_a_trd["Total horas"].apply(lambda x: str(x).split(" days ")[-1] if pd.notnull(x) else None)
df_input_a_trd["Janelas"] = (df_input_a_trd["Fim"] - df_input_a_trd["Início"]).dt.total_seconds() / 3600
df_input_a_trd["Janelas"] = df_input_a_trd["Janelas"].astype(int)
df_input_a_trd["Início"] = df_input_a_trd["Início"].dt.time
df_input_a_trd["Fim"] = df_input_a_trd["Fim"].dt.time
df_input_a_trd['Nutri'] = df_input_a['Unnamed: 6'].copy()
df_input_a_trd.drop(columns=['Mês_num'], inplace=True)
df_input_a_trd

,Data completa,Ano,Mês,Mês_Ano,DDS,Início,Fim,Total horas,Janelas,Nutri,Data
0,01/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,08:00:00,09:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-01
1,01/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,09:00:00,10:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-01
2,01/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,10:00:00,11:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-01
3,01/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,11:00:00,12:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-01
4,03/11/2025 - Seg,2025,Novembro,Novembro2025,Seg,07:00:00,09:00:00,02:00:00,2,DANIELLE CASTELLANI,2025-11-03
...,...,...,...,...,...,...,...,...,...,...,...
255,28/11/2025 - Sex,2025,Novembro,Novembro2025,Sex,14:00:00,15:00:00,01:00:00,1,MARIA CLARA LUZ DA SILVA,2025-11-28
256,29/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,08:00:00,09:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-29
257,29/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,09:00:00,10:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-29
258,29/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,10:00:00,11:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-29
259,29/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,11:00:00,12:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-29

In [5]:
def label_semana(df):
    s = df["Data"]           # sua coluna de datas
    mask = s.notna()

    m_ini = s.dt.to_period("M").dt.start_time
    m_fim = (m_ini + pd.offsets.MonthEnd(0))

    # 1) segunda e domingo da semana real (Seg–Dom)
    week_mon = s - pd.to_timedelta(s.dt.weekday, unit="D")       # segunda
    week_sun = week_mon + pd.Timedelta(days=6)                   # domingo

    # 2) ajusta para ficar dentro do mês
    week_start = week_mon.where(week_mon >= m_ini, m_ini)        # início = max(seg, 1º dia do mês)
    week_end   = week_sun.where(week_sun <= m_fim, m_fim)        # fim    = min(dom, último dia do mês)

    # 3) rótulo
    mes_abrev = {1:"Jan",2:"Fev",3:"Mar",4:"Abr",5:"Mai",6:"Jun",
                7:"Jul",8:"Ago",9:"Set",10:"Out",11:"Nov",12:"Dez"}

    w0 = m_ini.dt.weekday
    week_in_month = ((s.dt.day + w0 - 1) // 7 + 1).astype("Int64")

    label = pd.Series(pd.NA, index=s.index, dtype="string")
    label[mask] = (
        s[mask].dt.month.astype(str)
        + " " +
        s[mask].dt.month.map(mes_abrev)
        + " - Sem " + week_in_month[mask].astype(str)
        + " - " + week_start[mask].dt.day.astype(str).str.zfill(2)
        + " a " + week_end[mask].dt.day.astype(str).str.zfill(2)
    )

    df["Semana_mes"] = week_in_month
    df["Semana_label"] = label
    return df

In [6]:
df_input_a_trd = label_semana(df_input_a_trd)
df_input_a_trd

,Data completa,Ano,Mês,Mês_Ano,DDS,Início,Fim,Total horas,Janelas,Nutri,Data,Semana_mes,Semana_label
0,01/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,08:00:00,09:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-01,1,11 Nov - Sem 1 - 01 a 02
1,01/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,09:00:00,10:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-01,1,11 Nov - Sem 1 - 01 a 02
2,01/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,10:00:00,11:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-01,1,11 Nov - Sem 1 - 01 a 02
3,01/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,11:00:00,12:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-01,1,11 Nov - Sem 1 - 01 a 02
4,03/11/2025 - Seg,2025,Novembro,Novembro2025,Seg,07:00:00,09:00:00,02:00:00,2,DANIELLE CASTELLANI,2025-11-03,2,11 Nov - Sem 2 - 03 a 09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,28/11/2025 - Sex,2025,Novembro,Novembro2025,Sex,14:00:00,15:00:00,01:00:00,1,MARIA CLARA LUZ DA SILVA,2025-11-28,5,11 Nov - Sem 5 - 24 a 30
256,29/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,08:00:00,09:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-29,5,11 Nov - Sem 5 - 24 a 30
257,29/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,09:00:00,10:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-29,5,11 Nov - Sem 5 - 24 a 30
258,29/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,10:00:00,11:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-29,5,11 Nov - Sem 5 - 24 a 30
259,29/11/2025 - Sab,2025,Novembro,Novembro2025,Sab,11:00:00,12:00:00,01:00:00,1,JULIANA RIBEIRO DE MELO,2025-11-29,5,11 Nov - Sem 5 - 24 a 30

In [7]:
df_input_b = pd.read_excel(r'C:\Users\vhcna\OneDrive - Marca Saúde\Área de Trabalho\Freelas\Flua nutrição\arquivos originais\03 Modelo Agenda Ocupada Visão Semanal.xlsx')
df_input_b.head()

,CASO,DATA,HORA INICIAL - FINAL,TOTAIS,TIPO,BENEFICIARIO,RESPONSÁVEL
0,497375,01/11/2025 - Sab,08:00 - 08:45,00:45:00,NaN,Joseane de Jesus Peres,JULIANA RIBEIRO DE MELO
1,501384,01/11/2025 - Sab,09:00 - 09:45,00:45:00,NaN,Patrícia Araújo Crepalde,JULIANA RIBEIRO DE MELO
2,490431,01/11/2025 - Sab,10:00 - 10:45,00:45:00,NaN,Ariana Silva de Amorim,JULIANA RIBEIRO DE MELO
3,497000,01/11/2025 - Sab,11:00 - 11:45,00:45:00,NaN,Thayane Karolina Martins,JULIANA RIBEIRO DE MELO
4,498965,03/11/2025 - Seg,07:00 - 07:45,00:45:00,NaN,LARISSA PEREIRA PAIM,DANIELLE CASTELLANI

In [8]:
df_input_b_trd = df_input_b.copy()
df_input_b_trd.rename(columns={'DATA':'Data completa', 'RESPONSÁVEL':'Nutri'}, inplace=True)
df_input_b_trd["Data"] = df_input_b_trd["Data completa"].str.split(" -").str[0]
df_input_b_trd["Data"] = pd.to_datetime(df_input_b_trd["Data"], format="%d/%m/%Y", errors="coerce")
df_input_b_trd.head()

,CASO,Data completa,HORA INICIAL - FINAL,TOTAIS,TIPO,BENEFICIARIO,Nutri,Data
0,497375,01/11/2025 - Sab,08:00 - 08:45,00:45:00,NaN,Joseane de Jesus Peres,JULIANA RIBEIRO DE MELO,2025-11-01
1,501384,01/11/2025 - Sab,09:00 - 09:45,00:45:00,NaN,Patrícia Araújo Crepalde,JULIANA RIBEIRO DE MELO,2025-11-01
2,490431,01/11/2025 - Sab,10:00 - 10:45,00:45:00,NaN,Ariana Silva de Amorim,JULIANA RIBEIRO DE MELO,2025-11-01
3,497000,01/11/2025 - Sab,11:00 - 11:45,00:45:00,NaN,Thayane Karolina Martins,JULIANA RIBEIRO DE MELO,2025-11-01
4,498965,03/11/2025 - Seg,07:00 - 07:45,00:45:00,NaN,LARISSA PEREIRA PAIM,DANIELLE CASTELLANI,2025-11-03

In [9]:
df_input_b_trd = label_semana(df_input_b_trd)
df_input_b_trd.head()

,CASO,Data completa,HORA INICIAL - FINAL,TOTAIS,TIPO,BENEFICIARIO,Nutri,Data,Semana_mes,Semana_label
0,497375,01/11/2025 - Sab,08:00 - 08:45,00:45:00,NaN,Joseane de Jesus Peres,JULIANA RIBEIRO DE MELO,2025-11-01,1,11 Nov - Sem 1 - 01 a 02
1,501384,01/11/2025 - Sab,09:00 - 09:45,00:45:00,NaN,Patrícia Araújo Crepalde,JULIANA RIBEIRO DE MELO,2025-11-01,1,11 Nov - Sem 1 - 01 a 02
2,490431,01/11/2025 - Sab,10:00 - 10:45,00:45:00,NaN,Ariana Silva de Amorim,JULIANA RIBEIRO DE MELO,2025-11-01,1,11 Nov - Sem 1 - 01 a 02
3,497000,01/11/2025 - Sab,11:00 - 11:45,00:45:00,NaN,Thayane Karolina Martins,JULIANA RIBEIRO DE MELO,2025-11-01,1,11 Nov - Sem 1 - 01 a 02
4,498965,03/11/2025 - Seg,07:00 - 07:45,00:45:00,NaN,LARISSA PEREIRA PAIM,DANIELLE CASTELLANI,2025-11-03,2,11 Nov - Sem 2 - 03 a 09

In [10]:
df_output_c = df_input_a_trd.pivot_table(index='Semana_label',
                                         columns='Nutri',
                                         values='Janelas',
                                         aggfunc='sum',
                                         fill_value=0,
                                         dropna=False)
df_output_c['TOTAL'] = df_output_c.sum(axis=1)
df_output_c['CHECK'] = 'Oferta'

tb_temp = df_input_b_trd.pivot_table(index='Semana_label',
                                         columns='Nutri',
                                         values='CASO',
                                         aggfunc='count',
                                         fill_value=0,
                                         dropna=False)
tb_temp['TOTAL'] = tb_temp.sum(axis=1)
tb_temp['CHECK'] = 'Ocupação'

df_output_c = pd.concat([df_output_c, tb_temp])

del tb_temp

In [11]:
cols = list(df_output_c.columns)

# Identificar colunas especiais
col_check = ['CHECK']
col_total = ['TOTAL']

# Remover especiais da lista
middle_cols = [c for c in cols if c not in ['CHECK', 'TOTAL']]

# Ordenar as nutricionistas
middle_cols_sorted = sorted(middle_cols)

# Novo ordenamento final
new_order = col_check + middle_cols_sorted + col_total

df_output_c = df_output_c[new_order]
df_output_c = df_output_c.fillna(0)
df_output_c[middle_cols_sorted] = df_output_c[middle_cols_sorted].astype(int)
df_output_c = df_output_c.sort_index()
df_output_c

Nutri,CHECK,ALINE BATISTA RIBEIRO,ANA LUÍSA R. SZAJUBOK,ANDREIA DUTRA GONCALVES,DANIELLE CASTELLANI,ISADORA BEATRIZ ROSSI AMATO,JOSE RIBEIRO GOUVEIA NETO,JULIANA RIBEIRO DE MELO,MANOELA MARIOTTO LANZARA,MARIA CLARA LUZ DA SILVA,STEPHANY PATRICIA PEREZ MARTINEZ,TOTAL
Semana_label,,,,,,,,,,,,
11 Nov - Sem 1 - 01 a 02,Oferta,0,0,0,0,0,0,4,0,0,0,4
11 Nov - Sem 1 - 01 a 02,Ocupação,0,0,0,0,0,0,4,0,0,0,4
11 Nov - Sem 2 - 03 a 09,Oferta,16,20,16,8,12,0,24,0,26,16,138
11 Nov - Sem 2 - 03 a 09,Ocupação,10,14,16,7,12,0,19,0,13,15,106
11 Nov - Sem 3 - 10 a 16,Oferta,16,0,16,16,13,10,21,0,26,16,134
11 Nov - Sem 3 - 10 a 16,Ocupação,14,0,16,15,9,9,11,0,9,12,95
11 Nov - Sem 4 - 17 a 23,Oferta,16,30,16,16,8,10,22,0,26,16,160
11 Nov - Sem 4 - 17 a 23,Ocupação,7,11,13,11,6,7,16,0,4,5,80
11 Nov - Sem 5 - 24 a 30,Oferta,16,30,16,16,12,10,20,7,26,16,169
11 Nov - Sem 5 - 24 a 30,Ocupação,1,6,5,8,7,6,10,7,8,7,65

In [12]:
# 1) Tabela resumida por semana, separando Oferta e Ocupação em colunas
df_semana = df_output_c.pivot_table(
    index="Semana_label",
    columns="CHECK",
    values="TOTAL",
    aggfunc="sum",
    fill_value=0
)

# Garante as colunas, mesmo que alguma semana não tenha Ocupação ainda
for col in ["Oferta", "Ocupação"]:
    if col not in df_semana.columns:
        df_semana[col] = 0

# 2) Calcula percentuais
df_semana["Agenda Ocupação"] = (
    df_semana["Ocupação"] / df_semana["Oferta"]
).replace([np.inf, np.nan], 0) * 100

df_semana["Horários Vagos"] = (
    100 - df_semana["Agenda Ocupação"]
)

# Arredondar
df_semana["Agenda Ocupação"] = df_semana["Agenda Ocupação"].round(2)
df_semana["Horários Vagos"] = df_semana["Horários Vagos"].round(2)

df_semana

CHECK                     Ocupação  Oferta  Agenda Ocupação  Horários Vagos
Semana_label
11 Nov - Sem 1 - 01 a 02         4       4           100.00            0.00
11 Nov - Sem 2 - 03 a 09       106     138            76.81           23.19
11 Nov - Sem 3 - 10 a 16        95     134            70.90           29.10
11 Nov - Sem 4 - 17 a 23        80     160            50.00           50.00
11 Nov - Sem 5 - 24 a 30        65     169            38.46           61.54

In [13]:
# oferta por nutri
oferta_nutri = df_output_c[df_output_c["CHECK"] == "Oferta"].drop(columns=["CHECK"])

# ocupação por nutri
ocupacao_nutri = df_output_c[df_output_c["CHECK"] == "Ocupação"].drop(columns=["CHECK"])

# somatório total por coluna
oferta_total = oferta_nutri.sum()
ocupacao_total = ocupacao_nutri.sum()

percent_ocupacao = (ocupacao_total / oferta_total * 100).round(1)
percent_vago = (100 - percent_ocupacao).round(1)

df_percent_nutri = pd.DataFrame({
    "Oferta": oferta_total,
    "Ocupação": ocupacao_total,
    "% Ocupação": percent_ocupacao,
    "% Horários Vagos": percent_vago
})

df_percent_nutri

,Oferta,Ocupação,% Ocupação,% Horários Vagos
Nutri,,,,
ALINE BATISTA RIBEIRO,64,32,50.0,50.0
ANA LUÍSA R. SZAJUBOK,80,31,38.8,61.2
ANDREIA DUTRA GONCALVES,64,50,78.1,21.9
DANIELLE CASTELLANI,56,41,73.2,26.8
ISADORA BEATRIZ ROSSI AMATO,45,34,75.6,24.4
JOSE RIBEIRO GOUVEIA NETO,30,22,73.3,26.7
JULIANA RIBEIRO DE MELO,91,60,65.9,34.1
MANOELA MARIOTTO LANZARA,7,7,100.0,0.0
MARIA CLARA LUZ DA SILVA,104,34,32.7,67.3
STEPHANY PATRICIA PEREZ MARTINEZ,64,39,60.9,39.1
TOTAL,605,350,57.9,42.1

In [14]:
# Calculo da meta mensal
# Deve ser feito com inputs no dash

#custo_nutri_mes = input('Inclua o valor do custo com as nutricionistas no mês: ')
#impostos = input('Informe o percentual de imposto: ')
#valor_consulta_recebido = input('Inclua o valor recebido por consulta realizada: ')

custo_nutri_mes = 30000
impostos = 21.5
valor_consulta_recebido = 84

meta_agendamento = np.ceil(custo_nutri_mes * (1 + (impostos/100)) / valor_consulta_recebido)
meta_agendamento

np.float64(434.0)

In [15]:
oferta = df_semana['Oferta'].sum()
agendamentos = df_semana['Ocupação'].sum()
ocupacao = round(agendamentos / oferta * 100, 2)

print('#### KPI ####')
print()
print(f'Oferta de agendas no mês: {oferta}')
print(f'Agendas ocupadas no mês: {agendamentos}')
print(f'Taxa de ocupação no mês: {ocupacao}%')

#### KPI ####

Oferta de agendas no mês: 605
Agendas ocupadas no mês: 350
Taxa de ocupação no mês: 57.85%

In [16]:
print(f'Faturamento no mês: R${agendamentos * valor_consulta_recebido}')
print(f'Meta x Ocupação: {meta_agendamento} x {agendamentos}')
print(f'Meta x Ocupação: {meta_agendamento} - {agendamentos} = {meta_agendamento - agendamentos}')

Faturamento no mês: R$29400
Meta x Ocupação: 434.0 x 350
Meta x Ocupação: 434.0 - 350 = 84.0

In [ ]:
## ABAIXO TEMOS SANDBOX - DESCONSIDERAR DO STREAMLIT ##

In [17]:
df_input_b_trd['Data'].max()

Timestamp('2025-11-29 00:00:00')

In [ ]:
# agendamentos e ocupação até o momento

In [18]:
15 / 30

0.5

In [19]:
meta_proporcial = 15 / 30 * meta_agendamento
meta_proporcial

np.float64(217.0)

In [20]:
print(f'Meta Proprorcial x Ocupação: {meta_proporcial} x {agendamentos}')
print(f'Meta Proprorcial x Ocupação: {meta_proporcial} - {agendamentos} = {meta_proporcial - agendamentos}')

Meta Proprorcial x Ocupação: 217.0 x 350
Meta Proprorcial x Ocupação: 217.0 - 350 = -133.0

In [21]:
# fazer indicadores por mês

In [22]:
# comparação da meta semanal
# comparação da meta mensal
# quanto falta

In [23]:
# considerar 80% de ocupação da agenda como meta financeira
# fazer comparações de agendas geral e por nutri considerando essa meta